### PR TITLE
Update default value of master host in inventory template

### PR DESCRIPTION
**Pull request by matskiv**
## What
Updating the value based on this PR: https://github.com/integr8ly/installation/pull/677

Relevant code change: https://github.com/integr8ly/installation/pull/677/files#diff-671124057910da5bb44047033c60d55aL16

### CODE REVIEW

**Comment by tremes** [comment]
I am fine with that if it works :-)

**Comment by matskiv** [comment]
Now that I think about it - it's not compatible with 1.4 release. Let me fix that.

**Comment by trepel** [comment]
@matskiv good point. Since we support N and N-1 versions in RHPDS, we need to be able to install both versions there. If the installation process is different for each, we need to update the RHPDS system to be able to install both versions.

**Comment by matskiv** [comment]
I fixed some mistakes I made. This is ready for review now.

**Pull request merged**
