### PR TITLE
rearranged structure of integreatly jobs folder

### PR DESCRIPTION
**Pull request by pawelpaszki**
## What
rearranged structure of integreatly jobs folder - https://issues.jboss.org/browse/INTLY-2885

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@trepel @tremes can you please have a look? I will update the configure_jenkins script once we are happy with the changes

**Comment by tremes** [comment]
It's just minor but maybe I would keep all the nightly triggers in one directory (and wouldn't create delorean directory). Otherwise it looks OK.

**Comment by pawelpaszki** [comment]
@tremes - thanks. Updated it now. if you are happy I will push the changed conf jenkins script and ask for visual inspection too

**Comment by pawelpaszki** [comment]
Merging it. there should be no affect on current jobs given that configure_jenkins is updated, which it is

**Pull request merged**
