### PR TITLE
Update Jenkinsfile

### PR DESCRIPTION
**Pull request by jhellar**
## What

There is 1.15.0 OLM already - this special branch for tests is no longer needed. And also PREFIX needs to be set for test pipeline.

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@jhellar do you have any successful jenkins runs?

**Comment by jhellar** [comment]
@pawelpaszki first run in https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocp4-all-tests-executor/138/console

First browser test failed because of issue with initializing kubeconfig. The other tests failed because htpasswd not available any more. Will rerun it.

**Comment by pawelpaszki** [comment]
I think we still need to have hardcoded version of olm branch, because there is a risk that the makefile of master will stop working with the latest olm release image.

**Comment by jhellar** [comment]
Another run: https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ocp4-all-tests-executor/139/console

Again first browser test failed, but I think that is known issue - kubeconfig not initialized on slave. Last browser test (WT) failed because WT is not working yet on OS4.

**Comment by jhellar** [comment]
I've created jira for the failing test: https://issues.redhat.com/browse/INTLY-5130

**Pull request merged**
