### PR TITLE
INTLY-2266 - remove unused RELASE_VERSION parameter from testing pipe…

### PR DESCRIPTION
**Pull request by tremes**
…lines

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@tremes can you please update pipeline definitions triggers after merging?

**Comment by tremes** [comment]
@pawelpaszki I don't think it' so urgent :) They are updated each night automatically. Anyway thanks for checking.

**Comment by trepel** [comment]
Merged, I manually removed the RELEASE_VERSION from both pds nightly triggers since they are not updated each night automatically. fyi @tonyxrmdavidson - if there is some failure/error speaking about RELEASE_VERSION, it might be caused by my manual modifications.

**Comment by tremes** [comment]
Ahh yeah good point. Sorry and thanks :)

**Pull request merged**
