### PR TITLE
PDS pipelines - parameterize the cluster domain

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by trepel** [comment]
@tremes What about having that `open.redhat.com` as default? I think that this `example.opentlc.com` is used only as an interm solution for let's encrypt issue.

**Comment by tremes** [comment]
@trepel yes could be

**Comment by trepel** [comment]
@tremes Should not be CLUSTER_DOMAIN be added when you call pds-install from within the pds-testing-executor?

**Comment by tremes** [comment]
@trepel yep. Thanks

**Comment by tremes** [comment]
Running here https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/pds-testing-executor/409/

**Pull request merged**
