### PR TITLE
Template for installation smoke tests job.

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
@trepel Please take a look.

**Comment by tremes** [comment]
@trepel I think we should discuss this a little bit....

**Comment by trepel** [comment]
@tremes what to do with this one? I think we should move the smoke-tests from your fork to master here.

**Comment by tremes** [comment]
Added one more param for release version. @trepel feel free to merge it. We can discuss it at any time. Thanks

**Comment by trepel** [comment]
Looking at the https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/installation-smoke-tests/configure we use this for quite some time now, so I am going to merge. But this swallows the excepiton stack trace - see my comment in https://github.com/integr8ly/ci-cd/pull/18. We can improve that later.

**Pull request merged**
