### PR TITLE
Remove bastion slave after installation

### PR DESCRIPTION
**Pull request by matskiv**
## Motivation
Our Jenkins instance has growing number of leftover bastion slaves used by installation pipeline. This change will ensure that these slaves are removed after each installation. 

## What
a) add removal of bastion slave at the end of the job
b) fix indentation

## Verification Steps
Test the yaml file with jjb. 
Update the job.
Try running the job.
Check that bastion slave is not present after the job is finished.

P.S: I don't know why diff is so big. I just wrapped existing timeout block in try{}.

### CODE REVIEW

**Comment by trepel** [comment]
@matskiv ehm, jop, the diff is ugly, is the only real change that finally block ?

**Comment by trepel** [comment]
@matskiv have you considered added the slave removal to uninstallation-pipeline as well? This one also creates bastion slaves.

**Comment by matskiv** [comment]
> @matskiv have you considered added the slave removal to uninstallation-pipeline as well? This one also creates bastion slaves.

No, but I will do that.
Don't merge yet.

**Comment by matskiv** [comment]
@trepel I added this improvement into uninstallation pipeline as well. Can you review please?

**Pull request merged**
