### PR TITLE
Do not run anything on the Jenkins master node

### PR DESCRIPTION
**Pull request by tremes**

### CODE REVIEW

**Comment by tremes** [comment]
@mikenairn Can you check as well please?

**Comment by mikenairn** [comment]
I don't see any issues with it, but really if you don't care what node gets used, you shouldn't need to specify. Maybe you should just disable job execution of the master?

**Comment by tremes** [comment]
Yes good point. I changed master node to "Only build jobs with label expressions matching this node". So this could be sufficient.

**Comment by trepel** [comment]
@tremes cool, are we ok to close this one without merging? I would say yes, or would you like to merge anyway?

**Comment by tremes** [comment]
Nah...better to close

**Pull request closed without merging**
