### PR TITLE
moved old ocp4 install to archive and created new RHMI on os4 installation pipeline

### PR DESCRIPTION
**Pull request by pawelpaszki**
## What
Added simplified RHMI install pipeline 

## Verification
The pipeline is running here: https://integreatly-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/OS4/job/openshift4-rhmi-install/1/console

### CODE REVIEW

**Comment by pawelpaszki** [comment]
@tremes there was a whitespace in the default recipients param, which I now removed. Can you please have a quick glance again?

**Comment by tremes** [comment]
@pawelpaszki I think we need to rename the pipeline also in configure_jenkins.sh right?

**Comment by pawelpaszki** [comment]
yes. good point. thanks

**Comment by pawelpaszki** [comment]
@tremes done

**Pull request merged**
